---
- name: play with dict
  hosts: localhost
  gather_facts: false
  vars:
    student_records: [{
      "first": "Dhruv",
      "last": "Kumar",
      "mobile": "12345",
      "ctc": "10L",
      "address": {
        "city": "Ayodhya",
        "country": "India"
      }
    },
      {
       "first": "Raj",
        "last": "Singh",
        "mobile": "67890",
        "ctc": "30L",
        "address": {
          "city": "Delhi",
          "country": "India"
        }
      },
      {
        "first": "Mohan",
        "last": "Shri",
        "mobile": "112233",
        "ctc": "15L",
        "address": {
          "city": "Banalore",
          "country": "India"
        }
      }]
      
    employees:
      {
        "raj": {"mobile": 12345, "email": "raj@gmail.com", "city": "Delhi"},
        "dhruv": {"mobile": 456, "email": "dhruv@gmail.com", "city": "ayodhya"},
        "rajesh": {"mobile": 8976, "email": "rajesh@gmail.com", "city": "bangalore"},
        "rockey": {"mobile": 098765, "email": "rockey@gmail.com", "city": "bangalore"}
      }  
  tasks:
    - name: select and extract only city
      debug:
        msg: "{{ student_records | map(attribute='address') | map(attribute='city') | list }}"
        
    - name: select and extract city and country
      debug:
        msg: "{{ student_records | map(attribute='address') | list }}"        

    - name: attribute joined with single line
      debug:
        msg: "{{ student_records | map(attribute='first') | join(',') | list }}"

    - name: attribute joined with coma with single line
      debug:
        msg: "{{ student_records | map(attribute='first') | join(',') | list }}"

    - name: attribute joined with coma with single line
      debug:
        msg: "{{ student_records | map(attribute='first') | join(',') | list }}"
        
    - name: select only dhruv's record
      debug:
        msg: "{{ ['dhruv'] | map('extract', 'employees')}}"
        
# now want to remove some value from employees varialble

    - name: remove dhruv's record
      debug:
        msg: "{{ student_records[item|int] combine({'ctc':ommit }) }}"
      loop: "{{ range(student_records|length)|list }}"


    - name: combine suresh's record
      set_fact:
        student_records: '{{ student_records + combine({"first": "Suresh","last": "Kumar","mobile": "12345","ctc": "1L","address": {"city": "Jjaisal","country": "India"}}) }}'

    - debug: var=student_records

