---
- name: play with list
  hosts: localhost
  gather_facts: false

  tasks:
    - name: add ansible student name
      set_fact:
        ansible_student_list: "{{ ansible_student_list|default([]) + [item] }}"
      loop:
        - "Praveen"
        - "Dhurv"
        - "check"
        - "Value"
        - "where"
    - name: print ansible student name
      debug:
        var: ansible_student_list
